ethereum-optimism/optimism-tutorial

- package.json
- tslint.json
- yarn.lock
> Use `@eth-optimism/dev`

- README.md
> Add link to opcodes

- scripts/helpers.ts
Helper function was using Def__MyL2DepositedERC20 instead of the optimism contracts OVM_L1ERC20Gateway_Def
> Helper function was using Def__MyL2DepositedERC20 instead of the optimism contracts OVM_L1ERC20Gateway_Def 

- README.md
A clear and concise description of the features you're adding in this pull request.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> Changed .ts to .js

- .gitignore
- README.md
- package.json
- yarn.lock
Fixes #22.
This PR should be merged once [`@eth-optimism/hardhat-ovm`](https://github.com/ethereum-optimism/optimism/tree/master/packages/hardhat-ovm) has been published.
`gasPrice` is set to 0 until I have the time to figure a simple way to add ETH balances to instantiated L2 accounts.
> refactor: use monorepo

- README.md
Updated to specify the local ovm testing will be against an Optimistic Ethereum node (vs an Ethereum node).
> Minor README content updates

- deploy/ERC20.deploy.js
- test/erc20.test.js
- yarn.lock
This fix comes after the discovery made in https://github.com/ethereum-optimism/optimism/issues/664#issuecomment-832293814
> fix: l2geth-fix-returndata

- test/erc20.test.js
Minor update that fixes the tutorial for v0.3.0. Should only be merged when v0.3.0 is merged.
**Metadata**
- Fixes #28
> fix: update tutorial for 0.3.0

- truffle/README.md
I put it in the doc twice instead of once.
> Remove excess text

- truffle/dapp/truffle-config.ovm.js
Gas price and block gas limit was not set correctly for Kovan Optimism.
> Fix optimistic_kovan network config

- hardhat/README.md
- hardhat/dapp/hardhat.config.js
- truffle/README.md
Includes a link to the issue on Truffle (https://github.com/trufflesuite/truffle/issues/4217)
> Using Optimistic Kovan (or Ethereum) from Hardhat, and why Truffle is a problem

- hardhat/README.md
- hardhat/dapp/hardhat.config.js
A clear and concise description of the features you're adding in this pull request.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> Changed optimisticKovan to optimistic-kovan in Hardhat

- hardhat/README.md
- truffle/README.md
A clear and concise description of the features you're adding in this pull request.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> Fixed a couple of links

- core-util-watcher/README.md
- core-util-watcher/traceTx.sh
1. Added the `eth_getLogs` 10k block limitation to README.md
2. Added a warning about this issue to traceTx.sh
3. Changed infuraID to come from stdin, to reduce the chance of such a value leaking
> Several updates, mostly related to the 10k `eth_getLogs` limit

- l1-l2-deposit-withdrawal/package.json
- l1-l2-deposit-withdrawal/scripts/example.js
- l1-l2-deposit-withdrawal/yarn.lock
Closing: https://github.com/ethereum-optimism/optimism-tutorial/issues/58
Closing: ENG-1315
> Use `@etc-optimism/core-utils` instead of `@eth-optimism/watcher`

- core-util-watcher/index.js
- core-util-watcher/package.json
- core-util-watcher/traceTx.sh
- core-util-watcher/yarn.lock
> Changed to use the actual `@eth-optimism/core-utils`

- l1-l2-deposit-withdrawal/scripts/example.js
Closing: INT-154
Added because a user tried to transfer sUSD through the bridge, saw it didn't work, and then modified this sample code to do it.
> Adding a sanity check to ensure we're sending tokens to the correct place

- remix/README.md
> Remix tutorial (trivial, but I think we should have something)

- core-util-watcher/README.md
- dapptools/README.md
- hardhat/README.md
- remix/README.md
- standard-bridge-custom-token/README.md
- standard-bridge-standard-token/README.md
- truffle/README.md
I fixed all the broken I could find in the optimism-tutorial repo, let me know if you want me to change anything.
- Fixes #79
> updated broken links in readme

- .github/ISSUE_TEMPLATE/issues.md
- README.md
- cross-dom-bridge/README.md
- cross-dom-comm/README.md
- first-contract/README.md
- getting-started/README.md
- sdk-estimate-gas/README.md
- sdk-view-tx/README.md
- standard-bridge-custom-token/README.md
- standard-bridge-standard-token/README.md
> Fixes to README.md and the discord link

- .github/CODEOWNERS
@Nicca42 , we need a backup person to approve PRs during your vacation. Can you please merge this?
> feat(CODEOWNERS): Add backup

- sdk-estimate-gas/.env.example
- sdk-estimate-gas/README.md
- sdk-estimate-gas/gas.js
- sdk-estimate-gas/package.json
- sdk-estimate-gas/yarn.lock
Closing: DOCS-620
Also add `dotenv` to the tutorial instead of encoding values in the script itself
> feat(estimate-gas): Updated for Goerli

- cross-dom-bridge/.env.example
- cross-dom-bridge/README.md
- cross-dom-bridge/index.js
- cross-dom-bridge/package.json
- cross-dom-bridge/yarn.lock
Also commented out the ERC-20 because I need to revamp the standard-bridge-standard-token tutorial.
Closing: DOCS-618
> feat(xdom-bridge): Use Goerli, not Kovan.

- first-contract/README.md
Blocked on https://github.com/smartcontracts/chainid.link/pull/5 being merged.
Closing: DOCS-619
> feat(first-contract): Update for Goerli test network

- first-contract/README.md
I noticed this was needed while looking to see if I can plug Alchemy here (I couldn't, BTW).
> feat(first-contract): Added the Optimism Goerli faucet

- getting-started/README.md
1. Use the chainlink.id link
2. The optimism faucet
> feat(getting-started): Make remix more user friendly

- cross-dom-comm/README.md
- cross-dom-comm/foundry/src/Greeter.sol
- cross-dom-comm/hardhat/contracts/Greeter.sol
- ecosystem/opengsn/README.md
- getting-started/README.md
- getting-started/hardhat/package.json
- getting-started/truffle/package.json
- getting-started/waffle/test/mock-contract.test.ts
- sdk-estimate-gas/README.md
- standard-bridge-custom-token/README.md
- standard-bridge-custom-token/hardhat.config.js
> feat(*): Remove Kovan references - merge Oct 5th

- sdk-estimate-gas/.env.example
- sdk-estimate-gas/README.md
- sdk-estimate-gas/gas.js
- sdk-estimate-gas/package.json
- sdk-estimate-gas/yarn.lock
Also added command line options for execution instead of relying on code modifications.
Closing: DOCS-660
> feat(sdk-estimate-gas): Update to support bedrock-alpha

- cross-dom-bridge-erc20/index.js
- cross-dom-bridge-eth/index.js
- cross-dom-comm/hardhat/hardhat.config.js
- getting-started/hardhat/hardhat.config.js
- getting-started/truffle/truffle-config.js
- sdk-estimate-gas/gas.js
- standard-bridge-standard-token/hardhat.config.js
> fix(*): Add sanity checks for the mnemonic

- getting-started/README.md
As requested in https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1667409932541829
> feat(getting-started): Add a note about verifying contracts

- getting-started/README.md
- getting-started/hardhat/hardhat.config.js
- getting-started/truffle/truffle-config.js
- sdk-estimate-gas/README.md
- sdk-estimate-gas/gas.js
- sdk-estimate-gas/package.json
- sdk-estimate-gas/yarn.lock
The other tutorials are still work in progress for various reasons, so they'll be updated directly to beta
Closing: DOCS-704
> Update getting-started and sdk-estimate-gas to use bedrock beta instead of alpha

- getting-started/README.md
- sdk-estimate-gas/README.md
To the two tutorials that already work with bedrock.
> Add the bedrock beta explorer

- getting-started/README.md
- getting-started/brownie/.env.example
- getting-started/brownie/.gitattributes
- getting-started/brownie/.gitignore
- getting-started/brownie/brownie-config.yaml
- getting-started/brownie/contracts/Greeter.sol
> feat(getting-started): Add Brownie (Python framework)

- cross-dom-bridge-erc20/README.md
- cross-dom-comm/README.md
- ecosystem/attestation-station/README.md
- getting-started/README.md
- sdk-estimate-gas/README.md
- sdk-trace-tx/README.md
As requested in https://oplabs-pbc.slack.com/archives/C037YKXU971/p1673051596640399 by liam.
> feat(*): optimistic.etherscan.io -> explorer.optimism.io

- getting-started/README.md
As requested https://oplabs-pbc.slack.com/archives/C0214EMUUJ3/p1673266478628459?thread_ts=1673043113.352429&cid=C0214EMUUJ3
> feat(getting-started): Add list of development stacks

- getting-started/README.md
- getting-started/foundry/lib/package.json
- getting-started/foundry/lib/yarn.lock
- getting-started/truffle/truffle-config.js
> feat(getting-started): Update to Goerli Bedrock

- sdk-estimate-gas/README.md
- sdk-estimate-gas/gas.js
> feat(sdk-estimate-gas): Update to Goerli being on Bedrock

- cross-dom-bridge-erc20/README.md
- cross-dom-bridge-erc20/index.js
- cross-dom-bridge-erc20/package.json
- cross-dom-bridge-erc20/yarn.lock
- cross-dom-bridge-eth/README.md
- cross-dom-comm/README.md
Also add a note in all the cross-dom tutorials that this isn't for mainnet yet, and a link to what does work on mainnet (until it is upgraded).
Closing: DOCS-717
> Update the bridging erc20 tutorial to Bedrock

- sdk-trace-tx/README.md
- sdk-trace-tx/yarn.lock
> feat(sdk-trace-tx): Update for Bedrock Goerli

- first-contract/README.md
Also for Etherscan instead of Blockscout.
Closing: DOCS-718
> feat(first-contract): Update for Bedrock Goerli

- ecosystem/attestation-station/README.md
- ecosystem/attestation-station/contracts/AttestationProxy.sol
- ecosystem/attestation-station/contracts/AttestationStation.sol
- ecosystem/attestation-station/hardhat.config.js
- ecosystem/attestation-station/package.json
- ecosystem/attestation-station/yarn.lock
> feat(attestationStation): Read all attestations about an address, attestationProxy

- cross-dom-comm/README.md
- cross-dom-comm/foundry/lib/package.json
- cross-dom-comm/foundry/lib/yarn.lock
- cross-dom-comm/foundry/src/FromL1_ControlL2Greeter.sol
> feat(xdom-comm): Add back Foundry support

- cross-dom-bridge-eth/README.md
- cross-dom-bridge-eth/index.js
- cross-dom-bridge-eth/package.json
- cross-dom-bridge-eth/yarn.lock
> feat(xdom-comm-bridge-eth): Update to Bedrock Goerli

- standard-bridge-custom-token/README.md
To reduce that chance of people making mistakes that would compromise security.
> feat(std-bridge-custom-token): Add warning to the README

- cross-dom-bridge-erc20/README.md
- standard-bridge-custom-token/README.md
- standard-bridge-standard-token/README.md
As requested in https://oplabs-pbc.slack.com/archives/C0229H2N4MD/p1677854208990789?thread_ts=1677793120.544359&cid=C0229H2N4MD
> feat(ERC-20 bridge tutorials): Add weird ERC-20 warning

- op-stack/forced-withdrawal/.env.example
- op-stack/forced-withdrawal/.gitignore
- op-stack/forced-withdrawal/contracts/Greeter.sol
- op-stack/forced-withdrawal/hardhat.config.js
- op-stack/forced-withdrawal/package-lock.json
- op-stack/forced-withdrawal/package.json
- op-stack/forced-withdrawal/scripts/sample-script.js
- op-stack/forced-withdrawal/test/sample-test.js
Code for forced withdrawals (actual explanation will go in stack.optimism.io).
> feat(op-stack/forced-withdrawal): The code

- ecosystem/opengsn/README.md
> feat(eco/gsn): Remove grafana board

- README.md
- cross-dom-bridge-erc20/README.md
- cross-dom-bridge-eth/README.md
- cross-dom-comm/README.md
- ecosystem/alchemy/README.md
- ecosystem/attestation-station/contract-access/README.md
- ecosystem/opengsn/README.md
- ecosystem/tenderly/README.md
- first-contract/README.md
- getting-started/README.md
- sdk-estimate-gas/README.md
- sdk-estimate-gas/gas.js
- sdk-trace-tx/README.md
- sdk-view-tx/README.md
- standard-bridge-custom-token/README.md
- standard-bridge-standard-token/README.md
> feat(*): Optimism to OP Mainnet

- ecosystem/attestation-station/README.md
- ecosystem/attestation-station/contract-access/README.md
> feat(atst docs): Correct link to devdocs

- cross-dom-bridge-erc20/.env.example
- cross-dom-bridge-erc20/README.md
- cross-dom-bridge-erc20/index.js
- cross-dom-bridge-erc20/package.json
- cross-dom-bridge-erc20/yarn.lock
- cross-dom-bridge-eth/.env.example
- cross-dom-bridge-eth/README.md
- cross-dom-bridge-eth/index.js
- cross-dom-bridge-eth/package.json
- cross-dom-bridge-eth/yarn.lock
- cross-dom-comm/README.md
- cross-dom-comm/foundry/lib/package.json
- cross-dom-comm/foundry/lib/yarn.lock
- cross-dom-comm/hardhat/.env.example
- cross-dom-comm/hardhat/hardhat.config.js
- cross-dom-comm/hardhat/package.json
- cross-dom-comm/hardhat/yarn.lock
- sdk-estimate-gas/package.json
- sdk-estimate-gas/yarn.lock
- sdk-trace-tx/README.md
- sdk-trace-tx/package.json
- sdk-trace-tx/yarn.lock
- sdk-view-tx/package.json
- sdk-view-tx/yarn.lock
- standard-bridge-custom-token/README.md
- standard-bridge-custom-token/package.json
- standard-bridge-custom-token/yarn.lock
- standard-bridge-standard-token/README.md
- standard-bridge-standard-token/package.json
- standard-bridge-standard-token/yarn.lock
Also changed a few variable names to `OP_GOERLI` because I needed to rerun the code anyway to verify the change.
Closing: DEVRL-991
> Change tutorials to account for the fact that bedrock is now the SDK default

- getting-started/README.md
Closing: [DEVRL-1089](https://linear.app/optimism/issue/DEVRL-1089)
> feat(getting-started): Rename Optimism Monorepo to OP-Stack

- cross-dom-bridge-erc20/README.md
- cross-dom-bridge-eth/README.md
- cross-dom-comm/README.md
- sdk-estimate-gas/README.md
- sdk-trace-tx/README.md
- sdk-view-tx/README.md
- standard-bridge-custom-token/README.md
- standard-bridge-standard-token/README.md
Closing: [DEVRL-1050](https://linear.app/optimism/issue/DEVRL-1050)
> feat(*): Add notices that the SDK supports many chains
